### ISSUE TITLE
[Feature]: Number of steps in log

### ISSUE THREAD

**Issue by sputtering** [mashb1t/Fooocus#14]
### Prerequisites

- [X] I have checked that this is not a duplicate of an already existing [feature request](https://github.com/lllyasviel/Fooocus/issues)

### Is your feature request related to a problem? Please describe.

Sometimes I do tests with specific steps by adjusting the debug value "Forced Overwrite of Sampling Step". 

### Describe the idea you'd like

The number of steps should show up in the History Log. Or, more specifically, the value of the debug setting "Forced Overwrite of Sampling Step"

**Comment by mashb1t** [comment]
Solved as of https://github.com/mashb1t/Fooocus/commit/26601a99d154acc2dbef017118d05fe465ebd83e
