### ISSUE TITLE
[Bug]: --disable-preset-download causes a python error

### ISSUE THREAD

**Issue by ForgetfulWasAria** [mashb1t/Fooocus#20]
### Prerequisites

- [X] I have read the [Troubleshooting Guide](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md)
- [X] I have checked that this is not a duplicate of an already existing [issue](https://github.com/lllyasviel/Fooocus/issues)

### Describe the problem

I'm running your fork and I encountered an issue with a preset I had made. It looked like something with the model download, so I checked an unmodified preset that I had the model for. It worked until I added the `--disable-preset-download` option to the batch file. It's not a big deal to remove the option, but I did want to report it. I haven't used Fooocus in a few days so all I can say is that it worked a week ago.
Thanks for your fork and all of your hard work on the main branch too!

### Full console log output

```shell
.\run_anime.bat

A:\ai_stuff\programs\Fooocus>.\python_embeded\python.exe -s Fooocus\entry_with_update.py --preset anime --disable-preset-download
Already up-to-date
Update succeeded.
[System ARGV] ['Fooocus\\entry_with_update.py', '--preset', 'anime', '--disable-preset-download']
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Fooocus version: 2.1.865 (mashb1t)
Loaded preset: A:\ai_stuff\programs\Fooocus\Fooocus\presets\anime.json
Skipped model download.
Traceback (most recent call last):
  File "A:\ai_stuff\programs\Fooocus\Fooocus\entry_with_update.py", line 46, in <module>
    from launch import *
  File "A:\ai_stuff\programs\Fooocus\Fooocus\launch.py", line 124, in <module>
    config.default_base_model_name, config.checkpoint_downloads = download_models(
TypeError: cannot unpack non-iterable NoneType object
```

### Version

2.1.865 (mashb1t)

### Where are you running Fooocus?

Locally

### Operating System

Windows 11

### What browsers are you seeing the problem on?

Firefox

**Comment by mashb1t** [comment]
Thank you for reporting, fixed in main and https://github.com/lllyasviel/Fooocus/pull/1570
