### ISSUE TITLE
[Bug]: Invert mask tick box not working?

### ISSUE THREAD

**Issue by Psokratease** [mashb1t/Fooocus#85]
### Checklist

- [ ] The issue has not been resolved by following the [troubleshooting guide](https://github.com/lllyasviel/Fooocus/blob/main/troubleshoot.md)
- [ ] The issue exists on a clean installation of Fooocus
- [X] The issue exists in the current version of Fooocus
- [ ] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

Attempting to change background on an image using "modify image" within inpaint.  While the enhanced masking feature works to isolate subject, inversion of masking is unobtainable.

I have ran this on "Run" and "realistic", same results.

### Steps to reproduce the problem

1) Upload any image to inpaint tab, tick "enable masking features" box.
2) Use any "Generation model" such as SAM (any version).
3) Use "Detection prompt". In this case, I used "body".
4) Click "Generate mask from image" button.
5) Image masks correctly, Creating a white masked area of body.
6) Tick "Invert mask when generating" box.
7) Click "Generate mask from Image" button as before.
8) Mask selects subject exactly as before. ("Body" is still white, background black). No inverting.

### What should have happened?

An inversion of the masked area should have been produced after ticking the invert box and generating mask.

### What browsers do you use to access Fooocus?

Mozilla Firefox

### Where are you running Fooocus?

Locally

### Console logs

```Shell
To create a public link, set `share=True` in `launch()`.
model_type EPS
UNet ADM Dimension 2816
IMPORTANT: You are using gradio version 3.41.2, however version 4.44.1 is available, please upgrade.
--------
Using pytorch attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using pytorch attention in VAE
extra {'cond_stage_model.clip_l.text_projection', 'cond_stage_model.clip_l.logit_scale'}
left over keys: dict_keys(['cond_stage_model.clip_l.transformer.text_model.embeddings.position_ids'])
Base model loaded: D:\Forge\webui\models\Stable-diffusion\juggernautXL_v8Rundiffusion.safetensors
VAE loaded: None
Request to load LoRAs [('sd_xl_offset_example-lora_1.0.safetensors', 0.1)] for model [D:\Forge\webui\models\Stable-diffusion\juggernautXL_v8Rundiffusion.safetensors].
Loaded LoRA [D:\Forge\webui\models\Lora\sd_xl_offset_example-lora_1.0.safetensors] for UNet [D:\Forge\webui\models\Stable-diffusion\juggernautXL_v8Rundiffusion.safetensors] with 788 keys at weight 0.1.
Fooocus V2 Expansion: Vocab with 642 words.
D:\foocus\Fooocus_win64_2-6-0\Fooocus_win64_2-6-0\python_embeded\lib\site-packages\torch\_utils.py:831: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()
Fooocus Expansion engine loaded for cuda:0, use_fp16 = True.
Requested to load SDXLClipModel
Requested to load GPT2LMHeadModel
Loading 2 new models
[Fooocus Model Management] Moving model(s) has taken 0.36 seconds
Started worker with PID 2228
App started successful. Use the app with http://127.0.0.1:7865/ or 127.0.0.1:7865
```

**Comment by mashb1t** [comment]
This checkbox takes effect when processing the mask during image generation, not in mask creation. Changing this behavior would lead to double negation, which does not reflect the intended outcome.
