### ISSUE TITLE
[Feature Request]: Multi User with Login

### ISSUE THREAD

**Issue by techteam-pro-discount** [mashb1t/Fooocus#86]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do?

I would appreciate a User Login (username + password), because im using reverse proxy to share it and offer my gpu to my friends to generate nice AI pictures.

### Proposed workflow

1. Go to WebUI
2. Enter Username + Password
3. Click Login and generate Stuff
4. Auto Logout after 6h without activity

**Comment by mashb1t** [comment]
You can already achieve this 2 ways:
1. use the built-in auth.json file to create username/password for auth via Gradio
2. use your reverse proxy as centralized user auth system with SSO/basic auth
